### ISSUE TITLE
有文档吗

### ISSUE THREAD

**Issue by abrahamgreyson** [petronny/wxapp-annular-progressbar#3]

**Comment by kangour** [comment]
嗨，我们在用法和实现方式上对进度条进行了优化，仅需传入进度百分比即可看到动画。

项目地址：https://github.com/laobingm/wxapp-annular-progressbar

* 代码片段

[https://developers.weixin.qq.com/s/Fqlln4mt7f99](https://developers.weixin.qq.com/s/Fqlln4mt7f99)

* 效果图

![https://github.com/laobingm/wxapp-annular-progressbar/blob/master/screenshot.gif](https://github.com/laobingm/wxapp-annular-progressbar/blob/master/screenshot.gif)

## 使用方法

将进度调整为 40%

```JavaScript

  onReady: function() {
    this.setProgressbar(40)
  }

```

## 结构介绍

* wxml

界面主要 view 有五个，分别是：左右容器，左右圆以及中间的空白部分

* wxss

通过 clip 属性对超出容器的圆圈进行切割

* js

通过调整 transform 和 transition 值控制左右圆圈旋转


## 主要函数

* setProgressbar: (target)

target：进度条进度，支持传入一个大于 0 的数，如果比例大于 100，则用余数代替。

setProgressbar 是控制进度条变化的唯一函数；

函数内部通过传入的目标百分比计算出进度条旋转的方向、角度以及时长；

支持正向和反向调整进度；

左半圆变化时，会先填充右半圆；

右半圆变化时，也会先清空左半圆。

**Comment by abrahamgreyson** [comment]
谢谢！

**Comment by abrahamgreyson** [comment]
明白


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Kangour Aronld <notifications@github.com>
发送时间: 2019年6月12日 15:33
收件人: petronny/wxapp-annular-progressbar <wxapp-annular-progressbar@noreply.github.com>
抄送: 刘彦祖 <82011220@qq.com>, Author <author@noreply.github.com>
主题: 回复：[petronny/wxapp-annular-progressbar] 有文档吗 (#3)




嗨，我们在用法和实现方式上对进度条进行了优化，仅需传入进度百分比即可看到动画。
 
项目地址：https://github.com/laobingm/wxapp-annular-progressbar
  
代码片段 
 
https://developers.weixin.qq.com/s/Fqlln4mt7f99
  
效果图 
 

 
使用方法
 
将进度调整为 40%
   onReady: function() {     this.setProgressbar(40)   } 
 
结构介绍
  
wxml 
 
界面主要 view 有五个，分别是：左右容器，左右圆以及中间的空白部分
  
wxss 
 
通过 clip 属性对超出容器的圆圈进行切割
  
js 
 
通过调整 transform 和 transition 值控制左右圆圈旋转
 
主要函数
  
setProgressbar: (target) 
 
传入进度条比例 target。
 
setProgressbar 也是控制进度条变化的唯一函数，函数内部通过传入的目标百分比计算出进度条旋转的方向、角度以及时长。
 
支持正向和反向调整进度，传入的百分比如果大于 100，则以余数为调整进度的依据。
 
左半圆变化时，会先填充右半圆；右半圆变化时，也会先清空左半圆。
